### ISSUE TITLE
Exception caught by Neruina

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [AlanorMiga/Just-Enough-Guns#29]
java.lang.ClassCastException: class net.minecraft.world.entity.monster.Zombie cannot be cast to class net.minecraft.server.level.ServerPlayer (net.minecraft.world.entity.monster.Zombie and net.minecraft.server.level.ServerPlayer are in module minecraft@1.20.1 of loader 'TRANSFORMER' @5de335cf)
	at TRANSFORMER/jeg@0.9.0/ttv.migami.jeg.entity.projectile.ProjectileEntity.getHitResult(ProjectileEntity.java:413)
	at TRANSFORMER/jeg@0.9.0/ttv.migami.jeg.entity.projectile.ProjectileEntity.findEntityOnPath(ProjectileEntity.java:360)
	at TRANSFORMER/jeg@0.9.0/ttv.migami.jeg.entity.projectile.ProjectileEntity.m_8119_(ProjectileEntity.java:250)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$153(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$bla000$catchTickingEntities$notTheCauseOfTickLag(Level.java:4540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md302b38$lambda$tickWorlds$0$4(MinecraftServer.java:7893)
	at TRANSFORMER/dimthread@1.2.1/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:49)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md302b38$lambda$tickWorlds$1$3(MinecraftServer.java:7890)
	at TRANSFORMER/dimthread@1.2.1/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$3(ThreadPool.java:58)
	at TRANSFORMER/dimthread@1.2.1/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@21.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@21.0.5/java.lang.Thread.run(Thread.java:1583)

**Comment by MigaMiDev** [comment]
I will look into it

**Comment by MigaMiDev** [comment]
Alrighty, quick fix, thanks for bringing this to me! The fix will be uploaded next update!
